import { Share } from "react-native";

import { APP_NAME } from "./constants";
import { isCurrentMonth } from "./dateUtils";
import { formatCurrency } from "./format";
import { loadAllData } from "./storage";

export async function shareMonthlySummary(t) {
  const data = await loadAllData();
  const now = new Date();
  const monthName = now.toLocaleString("en-IN", { month: "long", year: "numeric" });

  const bills = data.bills.filter((item) => !item.paid && isCurrentMonth(item.dueDate));
  const autopay = data.autopay.filter((item) => !item.paid && isCurrentMonth(item.date));
  const tasks = data.tasks.filter((item) => !item.done && isCurrentMonth(item.dueDate));
  const warrantyAlerts = data.warranty.filter((item) => {
    const expiryDate = item.expiryDate;
    if (!expiryDate) return false;
    const today = new Date();
    const expiry = new Date(`${expiryDate}T00:00:00`);
    const days = Math.round((expiry - new Date(today.getFullYear(), today.getMonth(), today.getDate())) / 86400000);
    return days <= 7;
  });

  const billAmount = sumAmount(bills);
  const autopayAmount = sumAmount(autopay);
  const taskAmount = sumAmount(tasks);
  const total = billAmount + autopayAmount + taskAmount;

  const hasPending = bills.length || autopay.length || tasks.length || warrantyAlerts.length;
  const message = hasPending
    ? [
        `${APP_NAME} Monthly Summary`,
        "",
        `Month: ${monthName}`,
        "",
        `Monthly Pending Amount: ${formatCurrency(total)}`,
        "",
        "Bills:",
        `- Total bills pending: ${bills.length}`,
        `- Pending bill amount: ${formatCurrency(billAmount)}`,
        "",
        "Autopay:",
        `- Total subscriptions pending: ${autopay.length}`,
        `- Pending subscription amount: ${formatCurrency(autopayAmount)}`,
        "",
        "Tasks:",
        `- Total pending tasks: ${tasks.length}`,
        `- Pending task amount: ${formatCurrency(taskAmount)}`,
        "",
        "Warranty Alerts:",
        `- Expiring/Expired items: ${warrantyAlerts.length}`,
        "",
        `Generated by ${APP_NAME}`,
      ].join("\n")
    : t.shareNoData;

  await Share.share({ message });
}

function sumAmount(items) {
  return items.reduce((total, item) => total + Number(item.amount || 0), 0);
}
